/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Action = IDL.Nat;
export const TargetGroup = IDL.Text;
export const Time = IDL.Int;
export const CompletedAction = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Location = IDL.Text;
export const RKH = IDL.Record({
  'action' : Action,
  'targetGroup' : TargetGroup,
  'date' : Time,
  'completedAction' : CompletedAction,
  'document' : IDL.Opt(ExternalBlob),
  'image' : IDL.Opt(ExternalBlob),
  'numTargeted' : IDL.Nat,
  'place' : Location,
  'remarks' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NIP = IDL.Text;
export const FullName = IDL.Text;
export const WilayahKerja = IDL.Text;
export const Tugas = IDL.Text;
export const PhoneNumber = IDL.Text;
export const UserProfile = IDL.Record({
  'nip' : NIP,
  'signature' : IDL.Opt(ExternalBlob),
  'namalengkap' : FullName,
  'wilayahKerja' : WilayahKerja,
  'jabatan' : Tugas,
  'phoneNumber' : PhoneNumber,
  'unitKerja' : IDL.Text,
});
export const RKHWithUser = IDL.Record({ 'rkh' : RKH, 'user' : IDL.Principal });
export const Profile = IDL.Record({
  'nip' : NIP,
  'signature' : IDL.Opt(ExternalBlob),
  'namalengkap' : FullName,
  'wilayahKerja' : WilayahKerja,
  'jabatan' : Tugas,
  'phoneNumber' : PhoneNumber,
  'unitKerja' : IDL.Text,
});
export const UserSummary = IDL.Record({
  'user' : IDL.Principal,
  'totalReports' : IDL.Nat,
  'profile' : IDL.Opt(Profile),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRKH' : IDL.Func([RKH], [], []),
  'adminDeleteRKH' : IDL.Func([IDL.Principal, Action], [], []),
  'deleteRKH' : IDL.Func([Action], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateUserToken' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDayRKH' : IDL.Func([IDL.Principal, Time], [IDL.Vec(RKH)], ['query']),
  'getMonthRKH' : IDL.Func(
      [IDL.Principal, Time, Time],
      [IDL.Vec(RKH)],
      ['query'],
    ),
  'getMonthlyRecap' : IDL.Func([Time, Time], [IDL.Vec(RKHWithUser)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getWeekRKH' : IDL.Func(
      [IDL.Principal, Time, Time],
      [IDL.Vec(RKH)],
      ['query'],
    ),
  'getYearRKH' : IDL.Func(
      [IDL.Principal, Time, Time],
      [IDL.Vec(RKH)],
      ['query'],
    ),
  'getYearlyRecap' : IDL.Func([Time, Time], [IDL.Vec(RKHWithUser)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllRKH' : IDL.Func([], [IDL.Vec(RKHWithUser)], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerProfile' : IDL.Func([Profile, IDL.Opt(ExternalBlob)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Action = IDL.Nat;
  const TargetGroup = IDL.Text;
  const Time = IDL.Int;
  const CompletedAction = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Location = IDL.Text;
  const RKH = IDL.Record({
    'action' : Action,
    'targetGroup' : TargetGroup,
    'date' : Time,
    'completedAction' : CompletedAction,
    'document' : IDL.Opt(ExternalBlob),
    'image' : IDL.Opt(ExternalBlob),
    'numTargeted' : IDL.Nat,
    'place' : Location,
    'remarks' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NIP = IDL.Text;
  const FullName = IDL.Text;
  const WilayahKerja = IDL.Text;
  const Tugas = IDL.Text;
  const PhoneNumber = IDL.Text;
  const UserProfile = IDL.Record({
    'nip' : NIP,
    'signature' : IDL.Opt(ExternalBlob),
    'namalengkap' : FullName,
    'wilayahKerja' : WilayahKerja,
    'jabatan' : Tugas,
    'phoneNumber' : PhoneNumber,
    'unitKerja' : IDL.Text,
  });
  const RKHWithUser = IDL.Record({ 'rkh' : RKH, 'user' : IDL.Principal });
  const Profile = IDL.Record({
    'nip' : NIP,
    'signature' : IDL.Opt(ExternalBlob),
    'namalengkap' : FullName,
    'wilayahKerja' : WilayahKerja,
    'jabatan' : Tugas,
    'phoneNumber' : PhoneNumber,
    'unitKerja' : IDL.Text,
  });
  const UserSummary = IDL.Record({
    'user' : IDL.Principal,
    'totalReports' : IDL.Nat,
    'profile' : IDL.Opt(Profile),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRKH' : IDL.Func([RKH], [], []),
    'adminDeleteRKH' : IDL.Func([IDL.Principal, Action], [], []),
    'deleteRKH' : IDL.Func([Action], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateUserToken' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDayRKH' : IDL.Func([IDL.Principal, Time], [IDL.Vec(RKH)], ['query']),
    'getMonthRKH' : IDL.Func(
        [IDL.Principal, Time, Time],
        [IDL.Vec(RKH)],
        ['query'],
      ),
    'getMonthlyRecap' : IDL.Func(
        [Time, Time],
        [IDL.Vec(RKHWithUser)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getWeekRKH' : IDL.Func(
        [IDL.Principal, Time, Time],
        [IDL.Vec(RKH)],
        ['query'],
      ),
    'getYearRKH' : IDL.Func(
        [IDL.Principal, Time, Time],
        [IDL.Vec(RKH)],
        ['query'],
      ),
    'getYearlyRecap' : IDL.Func(
        [Time, Time],
        [IDL.Vec(RKHWithUser)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllRKH' : IDL.Func([], [IDL.Vec(RKHWithUser)], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerProfile' : IDL.Func([Profile, IDL.Opt(ExternalBlob)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };