/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Action = bigint;
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type CompletedAction = string;
export type ExternalBlob = Uint8Array;
export type FullName = string;
export type Location = string;
export type NIP = string;
export type PhoneNumber = string;
export interface Profile {
  'nip' : NIP,
  'signature' : [] | [ExternalBlob],
  'namalengkap' : FullName,
  'wilayahKerja' : WilayahKerja,
  'jabatan' : Tugas,
  'phoneNumber' : PhoneNumber,
  'unitKerja' : string,
}
export interface RKH {
  'action' : Action,
  'targetGroup' : TargetGroup,
  'date' : Time,
  'completedAction' : CompletedAction,
  'document' : [] | [ExternalBlob],
  'image' : [] | [ExternalBlob],
  'numTargeted' : bigint,
  'place' : Location,
  'remarks' : [] | [string],
}
export interface RKHWithUser { 'rkh' : RKH, 'user' : Principal }
export type TargetGroup = string;
export type Time = bigint;
export type Tugas = string;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'nip' : NIP,
  'signature' : [] | [ExternalBlob],
  'namalengkap' : FullName,
  'wilayahKerja' : WilayahKerja,
  'jabatan' : Tugas,
  'phoneNumber' : PhoneNumber,
  'unitKerja' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'user' : Principal,
  'totalReports' : bigint,
  'profile' : [] | [Profile],
}
export type WilayahKerja = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRKH' : ActorMethod<[RKH], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateUserToken' : ActorMethod<[Principal], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDayRKH' : ActorMethod<[Principal, Time], Array<RKH>>,
  'getMonthRKH' : ActorMethod<[Principal, Time, Time], Array<RKH>>,
  'getMonthlyRecap' : ActorMethod<[Time, Time], Array<RKHWithUser>>,
  'getProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getWeekRKH' : ActorMethod<[Principal, Time, Time], Array<RKH>>,
  'getYearRKH' : ActorMethod<[Principal, Time, Time], Array<RKH>>,
  'getYearlyRecap' : ActorMethod<[Time, Time], Array<RKHWithUser>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listAllRKH' : ActorMethod<[], Array<RKHWithUser>>,
  'listAllUsers' : ActorMethod<[], Array<UserSummary>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerProfile' : ActorMethod<[Profile, [] | [ExternalBlob]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];